version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12.x
        golang: 1.x
  build:
    commands:
      - make
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yml --parameter-overrides AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml