version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shiftemotion-lambda-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hc8lx1tkx0ma"
s3_prefix = "shiftemotion-lambda-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

