AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend para ShiftEmotion basado en AWS Lambda

Globals:
  Function:
    Timeout: 5

Resources:
  #Definición de la API
  ShiftEmotionBackendAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration: True

  JwtValidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: npm_services/jwtValidation/
      Handler: index.handler
      Runtime: nodejs12.x
      Tracing: Active

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: go_services/login/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ShiftEmotionBackendAPI
            Path: /login
            Method: GET

  LoginTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: go_services/login_token
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          AwsAK: !Ref AwsAccessKey
          AwsR: !Ref AwsRegion
          AwsSK: !Ref AwsSecretKey
      Events:
        GetRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ShiftEmotionBackendAPI
            Path: /login/token
            Method: POST

  RecomendacionInicialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: go_services/recomendacionInicial/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ShiftEmotionBackendAPI
            Path: /recomendaciones/home
            Method: GET

  HistorialFotosFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          AwsAK: !Ref AwsAccessKey
          AwsR: !Ref AwsRegion
          AwsSK: !Ref AwsSecretKey
      CodeUri: go_services/historialFotos/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ShiftEmotionBackendAPI
            Path: /recomendaciones/historial
            Method: GET

  RecomendacionFotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          AwsAK: !Ref AwsAccessKey
          AwsR: !Ref AwsRegion
          AwsSK: !Ref AwsSecretKey
      CodeUri: go_services/recomendacionFoto/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ShiftEmotionBackendAPI
            Path: /recomendaciones/historial/recomendacion
            Method: GET

  ObtenerPerfilFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          AwsAK: !Ref AwsAccessKey
          AwsR: !Ref AwsRegion
          AwsSK: !Ref AwsSecretKey
      CodeUri: go_services/obtenerPerfil/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref ShiftEmotionBackendAPI
            Path: /perfil
            Method: GET

Parameters:
  AwsAccessKey:
    Type: String
    Default: AWS_ACCESS_KEY_ID
  AwsRegion:
    Type: String
    Default: REGION
  AwsSecretKey:
    Type: String
    Default: AWS_SECRET_ACCESS_KEY