AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend para ShiftEmotion basado en AWS Lambda

Globals:
  Function:
    Timeout: 5

Resources:
  #Definición de la API
  ShiftEmotionBackendAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: jwtAuthorizer
        AddDefaultAuthorizerToCorsPreflight: False
        Authorizers:
          jwtAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt JwtValidationFunction.Arn
            Identity:
              Headers:
                - tokenHeader

  JwtValidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: npm_services/jwtValidation/
      Handler: index.handler
      Runtime: nodejs12.x
      Tracing: Active

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: go_services/login/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftEmotionBackendAPI
            Path: /login
            Method: GET
            Auth:
              Authorizer: NONE

  LoginTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: go_services/login_token
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: Api
          Properties:
            Environment:
              Variables:
                AWS_ACCESS_KEY_ID: AKIA4XYGNBVQ7HRMQXJB
                AWS_REGION: us-east-1
                AWS_SECRET_ACCESS_KEY: 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
            RestApiId: !Ref ShiftEmotionBackendAPI
            Path: /login/token
            Method: POST
            Auth:
              Authorizer: NONE

  RecomendacionInicialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: go_services/recomendacionInicial/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftEmotionBackendAPI
            Path: /recomendaciones/home
            Method: GET

  HistorialFotosFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: AKIA4XYGNBVQ7HRMQXJB
          AWS_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: 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
      CodeUri: go_services/historialFotos/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftEmotionBackendAPI
            Path: /recomendaciones/historial
            Method: GET

  RecomendacionFotoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: AKIA4XYGNBVQ7HRMQXJB
          AWS_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: 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
      CodeUri: go_services/recomendacionFoto/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftEmotionBackendAPI
            Path: /recomendaciones/historial/recomendacion
            Method: GET

  ObtenerPerfilFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: AKIA4XYGNBVQ7HRMQXJB
          AWS_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: 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
      CodeUri: go_services/obtenerPerfil/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ShiftEmotionBackendAPI
            Path: /perfil
            Method: GET
